---
http_interactions:
- request:
    method: post
    uri: "<PRENEEDS_HOST>/eoas_SOA/PreNeedApplicationPort"
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://service.soa.eoas.cem.va.gov/"
        xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><tns:receivePreNeedApplication><preNeedRequest><applicant><applicantEmail>hg@hotmail.com</applicantEmail><applicantPhoneNumber>555-555-5555
        - 234</applicantPhoneNumber><applicantRelationshipToClaimant>Self</applicantRelationshipToClaimant><completingReason>I
        don&#39;t know</completingReason><mailingAddress><address1>1st address line
        1</address1><address2>2nd address line 1</address2><address3>3rd address line
        1</address3><city>NY</city><countryCode>US</countryCode><postalZip>10000</postalZip><state>NY</state></mailingAddress><name><firstName>first_name1</firstName><lastName>last_name1</lastName><maidenName>maiden_name1</maidenName><middleName>middle_name1</middleName><suffix>Jr.</suffix></name></applicant><applicationStatus>somewhere</applicationStatus><claimant><address><address1>1st
        address line 2</address1><address2>2nd address line 2</address2><address3>3rd
        address line 2</address3><city>NY</city><countryCode>US</countryCode><postalZip>10000</postalZip><state>NY</state></address><dateOfBirth>2001-01-31</dateOfBirth><desiredCemetery>400</desiredCemetery><email>a@b.com</email><name><firstName>first_name2</firstName><lastName>last_name2</lastName><maidenName>maiden_name2</maidenName><middleName>middle_name2</middleName><suffix>Jr.</suffix></name><phoneNumber>1234567890</phoneNumber><relationshipToVet>1</relationshipToVet><ssn>123-45-6789</ssn></claimant><currentlyBuriedPersons><cemeteryNumber>400</cemeteryNumber><name><firstName>first_name3</firstName><lastName>last_name3</lastName><maidenName>maiden_name3</maidenName><middleName>middle_name3</middleName><suffix>Jr.</suffix></name></currentlyBuriedPersons><hasAttachments>false</hasAttachments><hasCurrentlyBuried>1</hasCurrentlyBuried><sendingApplication>vets.gov</sendingApplication><sendingCode>abc</sendingCode><sentTime>2017-07-20T10:42:20Z</sentTime><trackingNumber>yl0qwUo1yuRGGwrVSvVG</trackingNumber><veteran><address><address1>1st
        address line 3</address1><address2>2nd address line 3</address2><address3>3rd
        address line 3</address3><city>NY</city><countryCode>US</countryCode><postalZip>10000</postalZip><state>NY</state></address><currentName><firstName>first_name4</firstName><lastName>last_name4</lastName><maidenName>maiden_name4</maidenName><middleName>middle_name4</middleName><suffix>Jr.</suffix></currentName><dateOfBirth>2001-01-31</dateOfBirth><dateOfDeath>2001-01-31</dateOfDeath><gender>Male</gender><isDeceased>unsure</isDeceased><maritalStatus>Married</maritalStatus><militaryServiceNumber>123456789</militaryServiceNumber><placeOfBirth>Brooklyn,
        NY</placeOfBirth><serviceName><firstName>first_name5</firstName><lastName>last_name5</lastName><maidenName>maiden_name5</maidenName><middleName>middle_name5</middleName><suffix>Jr.</suffix></serviceName><serviceRecords><branchOfService>AF</branchOfService><dischargeType>1</dischargeType><enteredOnDutyDate>2001-01-31</enteredOnDutyDate><highestRank>GEN</highestRank><nationalGuardState>N</nationalGuardState><releaseFromDutyDate>2001-01-31</releaseFromDutyDate></serviceRecords><ssn>123-45-6789</ssn><vaClaimNumber>123456789</vaClaimNumber><militaryStatus>A</militaryStatus></veteran></preNeedRequest></tns:receivePreNeedApplication></env:Body></env:Envelope>
    headers:
      Accept:
      - text/xml;charset=UTF-8
      Content-Type:
      - text/xml;charset=UTF-8
      User-Agent:
      - Vets.gov Agent
      Date:
      - Thu, 20 Jul 2017 10:42:20 GMT
      Content-Length:
      - '3474'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 20 Jul 2017 10:42:20 GMT
      Transfer-Encoding:
      - chunked
      Content-Type:
      - multipart/related;start="<rootpart*fe62f13e-2139-4dbe-9f5c-bbc90a001c2c@example.jaxws.sun.com>";type="application/xop+xml";boundary="uuid:fe62f13e-2139-4dbe-9f5c-bbc90a001c2c";start-info="text/xml"
    body:
      encoding: UTF-8
      string: "--uuid:fe62f13e-2139-4dbe-9f5c-bbc90a001c2c\r\nContent-Id: <rootpart*fe62f13e-2139-4dbe-9f5c-bbc90a001c2c@example.jaxws.sun.com>\r\nContent-Type:
        application/xop+xml;charset=utf-8;type=\"text/xml\"\r\nContent-Transfer-Encoding:
        binary\r\n\r\n<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S=\"http://schemas.xmlsoap.org/soap/envelope/\"><S:Body><ns2:receivePreNeedApplicationResponse
        xmlns:ns2=\"http://service.soa.eoas.cem.va.gov/\"><return><applicationUUID>ba4e2557-33eb-46b6-80d8-95376a8855a0</applicationUUID><returnCode>200</returnCode><returnDescription>PreNeed
        Application received.</returnDescription></return></ns2:receivePreNeedApplicationResponse></S:Body></S:Envelope>\r\n--uuid:fe62f13e-2139-4dbe-9f5c-bbc90a001c2c--"
    http_version: 
  recorded_at: Thu, 20 Jul 2017 10:42:20 GMT
recorded_with: VCR 3.0.3
