fullName: [identity_information, full_name]
socialSecurityNumber: [identity_information, ssn]
gender: [identity_information, gender]
dateOfBirth: [identity_information, date_of_birth]
veteran: [veteran_contact_information, veteran]
directDeposit: [payment_information, payment_account]
disabilities: [rated_disabilities_information, rated_disabilities]
